"""add_v4_task_fields

Revision ID: 0d7a5b1aa72d
Revises: d1eb0d2363ec
Create Date: 2026-08-31 17:26:32.219099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d7a5b1aa72d'
down_revision: Union[str, Sequence[str], None] = 'd1eb0d2363ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('priority', sa.Enum('low', 'medium', 'high', name='task_priority'), nullable=False, server_default='medium'))
    op.add_column('tasks', sa.Column('status', sa.Enum('todo', 'in_progress', 'done', name='task_status'), nullable=False, server_default='todo'))
    op.add_column('tasks', sa.Column('due_date', sa.Date(), nullable=True))
    op.add_column('tasks', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'updated_at')
    op.drop_column('tasks', 'due_date')
    op.drop_column('tasks', 'status')
    op.drop_column('tasks', 'priority')
    # ### end Alembic commands ###
